package codegen

import (
	"testing"

	"github.com/stretchr/testify/assert"
)

const (
	packageName = "packageName"
	codeGen     = "my-nihongo-codegen"
)

func TestFileDeclaration(t *testing.T) {
	const want = `// Code generated by my-nihongo-codegen. DO NOT EDIT.
package packageName
`
	got := NewFile(packageName, codeGen).generate()

	assert.Equal(t, want, got)
}

func TestFileImport(t *testing.T) {
	const want = `// Code generated by my-nihongo-codegen. DO NOT EDIT.
package packageName
import (
"strings"
)
`
	got := NewFile(packageName, codeGen).
		Import("strings").
		generate()

	assert.Equal(t, want, got)
}

func TestFileImportAlias(t *testing.T) {
	const want = `// Code generated by my-nihongo-codegen. DO NOT EDIT.
package packageName
import (
str "strings"
)
`
	got := NewFile(packageName, codeGen).
		ImportAlias("strings", "str").
		generate()

	assert.Equal(t, want, got)
}

func TestFileImports(t *testing.T) {
	const want = `// Code generated by my-nihongo-codegen. DO NOT EDIT.
package packageName
import (
"os"
str "strings"
)
`
	got := NewFile(packageName, codeGen).
		Import("os").ImportAlias("strings", "str").
		generate()

	assert.Equal(t, want, got)
}
