package codegen

import (
	"os"
	"os/exec"
	"strings"
)

type file struct {
	stmts   []*stmt
	imports *importGroupStmt
}

// NewFile adds a package name and a comment that the file is auto-generated
func NewFile(packageName, generatorName string) *file {
	f := &file{stmts: make([]*stmt, 3), imports: importGroup()}
	ptr := new(stmt)
	*ptr = f.imports

	f.stmts[0] = commentF("Code generated by %s. DO NOT EDIT.", generatorName)
	f.stmts[1] = pkg(packageName)
	f.stmts[2] = ptr

	return f
}

// Save creates a new file for the generated code
func (f *file) Save(filePath string) error {
	if out, err := os.Create(filePath); err != nil {
		return err
	} else {
		if err = out.Truncate(0); err != nil {
			return err
		} else if _, err = out.Seek(0, 0); err != nil {
			return err
		} else if _, err = out.WriteString(f.generate()); err != nil {
			return err
		}

		exec.Command("gofmt", "-w", filePath).Run()
		return nil
	}
}

func (f *file) generate() string {
	var sb strings.Builder

	for _, stmt := range f.stmts {
		(*stmt).write(&sb)
	}

	return sb.String()
}

func (f *file) append(stmt *stmt) {
	f.stmts = append(f.stmts, stmt)
}
